---
# tasks file for Ubuntu
- name: nodejs | Ensure installed npm and nodejs.
  apt:
    name: ['nodejs', 'npm']
    state: present
  become: yes
  environment: "{{ proxy_env }}"

- name: nodejs | Ensure installed n.
  npm:
    name: n
    global: yes
  become: yes
  environment: "{{ proxy_env }}"

- name: nodejs | Ensure installed node stable.
  shell: n stable
  become: yes
  environment: "{{ proxy_env }}"

- name: nodejs | Purge nodejs and npm from APT.
  apt:
    name: ['nodejs', 'npm']
    purge: yes
  become: yes
  environment: "{{ proxy_env }}"

- name: nodejs | Ensure existing ~/.npm-global directory.
  file:
    path: ~/.npm-global
    state: directory

- name: nodejs | Ensure npm config setting.
  shell: npm config set prefix '~/.npm-global'


- name: nodejs | Ensure ~/.nps-global is set in PATH
  blockinfile:
    path: "{{ ansible_env.HOME}}/.bashrc"
    block: |
      export PATH="$HOME/.npm-global/bin:$PATH"
    marker: "#{mark} ANSIBLE MANAGED BLOCK - nodejs"
  become: no
  environment: "{{ proxy_env }}"
