---
# tasks for Ubuntu
- name: coq | Ensure packages installed(APT).
  apt:
    name: ['pkg-config', 'libgtksourceview2.0-dev']
    state: present
  become: yes
  environment: "{{ proxy_env }}"

- name: coq | Add Coq repository.
  shell: opam repo add coq-released https://coq.inria.fr/opam/released
  environment: "{{ proxy_env }}"

- name: coq | Ensure Coq installed.
  shell: opam install -y coq.8.9.1
  environment: "{{ proxy_env }}"

- name: coq | Ensure CoqIDE installed.
  shell: opam install -y coqide.8.9.1
  environment: "{{ proxy_env }}"
