---
# tasks for Ubuntu
- name: haskell | Ensure install Haskell
  apt:
    name: ['haskell-platform', 'curl']
    state: present
  become: yes
  environment: "{{ proxy_env }}"

- name: haskell | Ensure install Stack
  shell: curl -sSL https://get.haskellstack.org/ | sh
  ignore_errors: yes
  environment: "{{ proxy_env }}"
